name: go lint
# Run this separately from pre-commit since then we get nice inline messages in PRs.

on:
  workflow_call:

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.10'
      - name: Configure Git
        run: |
          git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"
          go env -w GOPRIVATE="github.com/piplabs/*"
          go clean -modcache
          go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1
          # Verbose with color. Just fail, don't fix issues. Use both annotations and normal output.
          args: -v --color=always --fix=false --timeout=10m --out-format=colored-line-number,github-actions
